apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  namespace: gonamespace
  labels:
    app: gowebapp
  name: gowebapp-dep
spec:
  selector:
    matchLabels:
      app: gowebapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      namespace: gonamespace
      labels:
        app: gowebapp
    spec:
      containers:
      - image: birdpedia-app
        name: birdpedia-app
        resources: {}
        imagePullPolicy: Never
        ports:
          - containerPort: 8081
status: {}
