apiVersion: apps/v2
kind: Deployment
metadata:
  creationTimestamp: null
  namespace: gonamespace
  labels:
    app: gowebapp
  name: gowebapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gowebapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      namespace: gonamespace
      labels:
        app: gowebapp
    spec:
      containers:
      - image: birdpedia-app
        name: gowebapp
        resources: {}
        imagePullPolicy: Never
        ports:
          - containerPort: 8081
status: {}
